import './globals.css';
import Script from 'next/script';
import type {Metadata} from 'next';
import {ToastProvider} from '@/components/Toast';
import {Geist, Geist_Mono} from 'next/font/google';
import ApolloWrapper from '@/utils/ApolloWrapper';

const geistSans = Geist({subsets: ['latin'], variable: '--font-geist-sans'});
const geistMono = Geist_Mono({subsets: ['latin'], variable: '--font-geist-mono'});

export const metadata: Metadata = {title: 'Create Next App', description: 'Generated by create next app'};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script
          strategy="beforeInteractive"
          src={`https://www.google.com/recaptcha/enterprise.js?render=${process.env.NEXT_PUBLIC_CAPTCHA_KEY}`}
        />
        <ApolloWrapper>
          <ToastProvider>{children}</ToastProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
